language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: MYEHhXMUs4OdlO/2X0MRNjzwVoEvAhgJz8qbRsrlhCrjUSxBI/lSy4XbzDz7qsYgmMr1nd6Yn4dKkJri6T1coxieMvYTdCWOaqHNld0XWmXntUwZWTl/FEISD/vWPdxuLK90Wb9RNIxVGZT4iMSlRQNYJMa2V7Ylu757A51ru+VQPuXxhlHRQLJgHmDOJ9nRHTBabvI4YvtH8FiEkIUP8XNWQjQAr4cp4K4jmilV59WNv1+L4vKh4VZ/TQcO/yc2Krk3D/HFMy1KTUwg+vKIWugsFfVxBleGYNwIBWMKPhT1VnyhiAIyOtFBH8XwCA+8j3tOnBGMWFZTUKzoS9hRJADfP7WQdqryif91IG9V1IsVgBaB03TDZg4AYKRG0Pe9lar3GdxU7QzxHNRIx8qaGEm8ZH9XRZtZqbcETrTnU8BX1TdNs5fT5dLvhhWYuj23q/KgsI5uCfmR6dOTARhcwha65KiT6qXb+UThbu+0t5owR1C+5nZ6eDTEd8plpDFa3/TEeYz7sytLd9xs7O4S1d5xF5yKgWJtyTY9kc3EBqBXBobdRrPspfagAWmoa9K0vxOWC7HIHaOfLsLqMdwHH+iw84FIE3EzOSVs5ZNFgjQ7lWlptq54dCAlznToktXzX1XdMoQovZtK8+IOKhItyeJAGIuCrVZ1K9EdCnB1SZs=
  app: vibrant-madame-35719
  on:
    repo: RodrigoSantelices/HotColdTest
